name: CI

on:
  push:
    branches:
    - testreport 
jobs:
  build_and_test:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Solution1/UnitTest.sln'

    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x


    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG
      
    - name: Test
      run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --logger "trx;LogFileName=test-results.trx" || true
    - name: Perform a Pester test from the Tests.ps1 file
      shell: pwsh
      run: |     
        echo "*****"        
        $Path ="./Solution1/UnitTestProject/TestResults/test-results.trx"
        [xml]$FileContent = Get-Content -Path $Path
        $UnitTestResults=$FileContent.TestRun.Results.UnitTestResult
        $count=$UnitTestResults.count
        $Passed =0
        $failed=0
        Write-Host "Unti test resutl count is : $count"
        foreach($UnitTestResult in  $UnitTestResults)
        {
        if($UnitTestResult.outcome -eq "Passed")
        {
        $Passed=$Passed+1
        Write-Host 
        }
        elseif($UnitTestResult.outcome -eq "Failed")
        {
         $failed= $failed+1
        }
        }
        Write-Host  $Passed
        Write-Host $failed
        $failedpercentage =  ($failed/$count) * 100  #$failed * ($count / 100)
        $passpercentage =  ($Passed/$count) * 100 
        Write-Host "failed percentage is : $failedpercentage"
        Write-Host "passed percentage is : $passpercentage"
      
